name: Memento Deps

on:
  schedule:
    - cron: "10 0 1 * *"

jobs:
  deps-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create the issue
        uses: imjohnbo/issue-bot@v3
        with:
          assignees: "fkoksal"
          title: Upgrade dependencies
          body: |-
            I'm a bot and I'm here to remind you to upgrade your dependencies. :robot:
          pinned: false
